version: '3.7'

services:

  database:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=curso
    volumes:
      - db-data:/var/lib/mysql:rw
      - './init_db:/docker-entrypoint-initdb.d'

  grafana:
    image: grafana/grafana:9.1.8
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - grafana-logs:/var/log/grafana

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  db-data:
  grafana-lib:
  grafana-logs:
